"""Generate routing-table.md for the /lenny router skill.

Usage: python gen_routing_table.py <library_dir> <categories_json> <out_md>
library_dir = <pkg>/references/lenny  (contains <skill>/SKILL.md)

Stdlib only. Portable across agents — output is plain markdown.
"""
import json
import re
import sys
from pathlib import Path


def frontmatter_desc(skill_md: Path) -> str:
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"^---\s*\n(.*?)\n---", text, re.S)
    if not m:
        return ""
    d = re.search(r"^description:\s*(.+)$", m.group(1), re.M)
    return re.sub(r"\s+", " ", d.group(1)).strip() if d else ""


def one_line(desc: str, limit: int = 160) -> str:
    # Upstream descriptions are single long sentences; trim at a word.
    if len(desc) <= limit:
        return desc
    cut = desc[:limit].rsplit(" ", 1)[0]
    return cut + "\u2026"


def main() -> int:
    lib, cat_path, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    cats = json.loads(cat_path.read_text(encoding="utf-8"))
    on_disk = {p.name for p in lib.iterdir()
               if (p / "SKILL.md").exists() and not p.name.startswith(("_", "."))}
    mapped = {s for v in cats.values() for s in v}
    ungrouped = sorted(on_disk - mapped)
    missing = sorted(mapped - on_disk)
    if missing:
        print(f"WARNING: mapped but not on disk: {missing}", file=sys.stderr)
    if ungrouped:
        cats.setdefault("Uncategorized", []).extend(ungrouped)
        print(f"NOTE: auto-grouped ungrouped skills: {ungrouped}", file=sys.stderr)

    lines = [
        "<!-- GENERATED by scripts/gen_routing_table.py - do not edit by hand; "
        "re-run scripts/sync_lenny_skills.py -->",
        "",
        "# Lenny skills routing table",
        "",
    ]
    total = 0
    for cat, skills in cats.items():
        lines.append(f"## {cat}")
        lines.append("")
        for s in skills:
            md = lib / s / "SKILL.md"
            if not md.exists():
                continue
            desc = one_line(frontmatter_desc(md))
            extra = ""
            if (md.parent / "references" / "artifacts.md").exists():
                extra = " + `artifacts.md`"
            lines.append(
                f"- **{s}** \u2014 {desc} "
                f"\u2192 `references/lenny/{s}/SKILL.md`{extra}"
            )
            total += 1
        lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} with {total} skills in {len(cats)} categories.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
